# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
# PyQt5.QtWebKitWidgets import *
import sys
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 850)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/icon.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open = QtWidgets.QPushButton(self.centralwidget)
        self.open.setGeometry(QtCore.QRect(50, 358, 90, 30))
        self.open.setObjectName("open")
        self.close_ = QtWidgets.QPushButton(self.centralwidget)
        self.close_.setGeometry(QtCore.QRect(50, 404, 90, 30))
        self.close_.setObjectName("close_")
        self.dete = QtWidgets.QPushButton(self.centralwidget)
        self.dete.setGeometry(QtCore.QRect(50, 310, 90, 30))
        self.dete.setObjectName("dete")
        self.text = QtWidgets.QLineEdit(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(50, 250, 90, 30))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        self.text.setFont(font)
        self.text.setObjectName("text")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(345, 225, 640, 480))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(500, 30, 330, 80))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(29)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.header.setFont(font)
        self.header.setObjectName("header")
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(50, 490, 90, 30))
        self.logout.setObjectName("logout")
        self.boder = QtWidgets.QLabel(self.centralwidget)
        self.boder.setGeometry(QtCore.QRect(195, 90, 900, 700))
        self.boder.setObjectName("boder")
        #self.logo1 = QtWidgets.QLabel(self.centralwidget)
        #self.logo1.setGeometry(QtCore.QRect(20, 559, 160, 240))
        #self.logo1.setObjectName("logo1")
        self.bgcolor = QtWidgets.QLabel(self.centralwidget)
        self.bgcolor.setGeometry(QtCore.QRect(0, 0, 1150, 850))
        self.bgcolor.setText("")
        self.bgcolor.setObjectName("bgcolor")
        self.countdown = QtWidgets.QLabel(self.centralwidget)
        self.countdown.setGeometry(QtCore.QRect(525, 150, 280, 60))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.countdown.setFont(font)
        self.countdown.setAlignment(QtCore.Qt.AlignCenter)
        self.countdown.setObjectName("countdown")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 30, 90, 120))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.openfile = QtWidgets.QPushButton(self.centralwidget)
        self.openfile.setGeometry(QtCore.QRect(50, 190, 90, 30))
        self.openfile.setObjectName("openfile")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setGeometry(QtCore.QRect(50, 445, 90, 30))
        self.help.setObjectName("help")
        self.bgcolor.raise_()
        self.boder.raise_()
        self.open.raise_()
        self.close_.raise_()
        self.dete.raise_()
        self.text.raise_()
        self.label.raise_()
        self.header.raise_()
        self.logout.raise_()
        #self.logo1.raise_()
        self.countdown.raise_()
        self.label_2.raise_()
        self.openfile.raise_()
        self.help.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open.setText(_translate("MainWindow", "打开摄像头"))
        self.close_.setText(_translate("MainWindow", "关闭摄像头"))
        self.dete.setText(_translate("MainWindow", "确定姓名"))
        self.label.setText(_translate("MainWindow", "人脸采集区域"))
        #self.header.setText(_translate("MainWindow", "人脸采集系统"))
        self.logout.setText(_translate("MainWindow", "注销"))
        #self.logo1.setText(_translate("MainWindow", "logo1"))
        self.countdown.setText(_translate("MainWindow", "采集等待中"))
        self.openfile.setText(_translate("MainWindow", "打开"))
        self.help.setText(_translate("MainWindow", "帮助中心"))
        #self.label.setStyleSheet("border:2px solid white;color:red;")
        self.countdown.setStyleSheet("border-color:white;border:2px;color:red;")
        self.open.setStyleSheet("QPushButton:hover{color:rgb(255,0,0)}""QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;}")
        #self.open.setFlat(true);
        self.close_.setStyleSheet("QPushButton:hover{color:rgb(255,0,0)}""QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;}")
        self.dete.setStyleSheet("QPushButton:hover{color:rgb(255,0,0)}""QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;}")
        self.help.setStyleSheet("QPushButton:hover{color:rgb(255,0,0)}""QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;}")
        self.openfile.setStyleSheet("QPushButton:hover{color:rgb(255,0,0)}""QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;}")
        self.logout.setStyleSheet("QPushButton:hover{color:rgb(255,0,0)}""QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;}")
        